spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.99.100:3306/user_service
      username: usr_user
      password: 260a87a10ddd9dc9e7f04f05d746a532
  application:
    name: user-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
server:
  port: 7200