spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.99.100:3306/user_service
      username: usr_user
      password: 260a87a10ddd9dc9e7f04f05d746a532
      sql-script-encoding: UTF-8
      initialization-mode: always
  application:
    name: user-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
security:
  oauth2:
    resource:
      jwt:
        key-value: -----BEGIN PUBLIC KEY-----
                   MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwySCnVbkvES/mMHJllnN
                   M5lQ9m26uXbbJzohBhCQyRe/wvuC1UqXDNd45VsgGWk2zZ9/36EH0DZLrrTMR487
                   Xqa+/OWm1ZDlNRKJDBcHv/WWcx1XULS3uC3hvcz/7kFTQTj80vvfhtUOfl7mXMh7
                   hznvKqB2oe067ZDzigqlDPjBCVpmGC77aHcw7HF4NVnsDki8oHUs9uEB2IHDrcpY
                   cSUivEwI2cN1mWDSQtoH3WRxHe39nIE748tLatkjvmKLzArugbuWh3his10DAVfU
                   Lg3kLRDtIBadvxxRZPqjyeSjFL0ti8yO4Dahyg4iDrBhY2Xc9kUeZssRxETbxmu0
                   BQIDAQAB
                   -----END PUBLIC KEY-----
server:
  port: 7200